### ISSUE TITLE
設定預設下單金額跟倍率

### ISSUE THREAD

**Issue by myhungtos** [hilezir/etoro-better-ui#1]
感謝使用tampermonkey設計更friendly的介面。

不知道可不可以額外評估此功能:
按下商品[交易鈕]跳出的視窗內的基本設定數值，可以透過tampermonkey內的script修改嗎?目前介面都會是預設是非一倍槓桿很容易不小心使用到槓桿，希望永遠打開預設都先是x1，另外下單金額也都永遠是保持全部資金的5%，不知道可不可以改成使用者自己決定?謝謝你。

**Comment by hilezir** [comment]
我有注意到這個需求，用 tampermonkey 其實可以的，但判定框框打開，有一些性能問題還未解決，而且用腳本改實際下單框框其實是有風險的，也許會因為腳本壞掉，或網站改版而造成錯誤，發生無法下單的情況。因此還需要更多時間，多加評估。

**Comment by myhungtos** [comment]
原來如此,如果怕整個功能失效跟效能問題，設計上保留原來的交易鈕，在旁邊弄一個自己的客製化的交易鈕行為跟原本的一樣，但是帶出的設定不一樣，這樣是可以的嗎？謝謝你。

**Comment by myhungtos** [comment]
另外etoro系統有一個一鍵交易的功能，是在系統內可以自己設定，商品，預設金額跟倍數，但是這個功能啟動後要在wachlist介面按，不知道可不可以，整合到trade按鈕送出後的小視窗內，因為裡面的報價比watchlist介面清楚，下單價格比較精準，謝謝

**Comment by hilezir** [comment]
> 原來如此,如果怕整個功能失效跟效能問題，設計上保留原來的交易鈕，在旁邊弄一個自己的客製化的交易鈕行為跟原本的一樣，但是帶出的設定不一樣，這樣是可以的嗎？謝謝你。

可以，我也一直在洗澡的時候想這個方案的 UI。

> 另外etoro系統有一個一鍵交易的功能，是在系統內可以自己設定，商品，預設金額跟倍數，但是這個功能啟動後要在wachlist介面按，不知道可不可以，整合到trade按鈕送出後的小視窗內，因為裡面的報價比watchlist介面清楚，下單價格比較精準，謝謝

啟動後要在 watchlist 按，是 etoro 的設計。我也有注意到這個問題，個人是滿容易按一下就出去了。而且也不好改。整合到下單框框內的方案，我會和前述功能一起考慮。

謝謝你的分享，你的具體細節數值分享，有助於更廣的使用者體驗參考方向。

**Comment by hilezir** [comment]
提供你目前開發中，的一個版本。

如果你有何想法，也可以再互相激盪一下。

![image](https://user-images.githubusercontent.com/1500206/79669739-494ae280-81f0-11ea-87bc-b8f390beacc4.png)

**Comment by myhungtos** [comment]
測試了一下新版有幾個想法跟你討論

1.金額的部分可能要改成跟原本介面一樣是提供自有資金的某種%當成一筆下單的金額
可能會比較萬用 一點例如5%， 10%， 20%， 30%， 40%，50%

2.設定完一次之後可以多一個打勾的鎖定功能，之後再開視窗就可以不用再按嗎?

3.有些商品例如:  https://www.etoro.com/markets/aoa 交易介面跟上面的btc不一樣就沒有帶出設定介面

上面一些建議給你參考，感謝你的用心開發。

**Comment by hilezir** [comment]
> 1.金額的部分可能要改成跟原本介面一樣是提供自有資金的某種%當成一筆下單的金額
可能會比較萬用 一點例如5%， 10%， 20%， 30%， 40%，50%

OK，考慮到每個人狀況不同，我考慮開發一個設定介面，讓使用者自行輸入每個人所想要的數值。這樣這個功能就能擴大符合需求。

> 2.設定完一次之後可以多一個打勾的鎖定功能，之後再開視窗就可以不用再按嗎?
理論上是可以的

應該是可以的。

> 3.有些商品例如: https://www.etoro.com/markets/aoa 交易介面跟上面的btc不一樣就沒有帶出設定介面

目前解決 `[ng-if]` 的性能問題方式，是以 `jQuery('body').delegate` 方式委任「會帶下單交易的按鈕」的事件，避免傳統 `setInterval` 的性能問題。

但上述方法，已知問題是在 「我的投資 https://www.etoro.com/portfolio/ko 」這個頁面，會無法委任成功（無法帶出介面），目前沒有更好的解決方案。有的話你可以提供看看。

---

而你說的「 https://www.etoro.com/markets/aoa 」頁面，我這邊實測是會正常帶出介面的。所以你能提供一下你的操作流程，和瀏覽器 console.panel 提供參考嗎？

如果有影片檔更好，我能更清楚觀察你的操作方式，以及 console.panel 錯誤訊息。

**Comment by myhungtos** [comment]
[11.zip](https://github.com/hilezir/etoro-better-ui/files/4510528/11.zip)
附件檔案是我用windows的問題步驟收錄程式製作出來的，在watchlist打開AOA沒有下單快速介面
但是打開黃金是有的

**Comment by hilezir** [comment]
> [11.zip](https://github.com/hilezir/etoro-better-ui/files/4510528/11.zip)
> 附件檔案是我用windows的問題步驟收錄程式製作出來的，在watchlist打開AOA沒有下單快速介面
> 但是打開黃金是有的

你的 11.zip 我解開後無法開啟，因為我是用 macOS。

能否請你提供錄影檔？

![貼上的影像_2020_4_25_上午1_08](https://user-images.githubusercontent.com/1500206/80238662-61f44600-8691-11ea-80a9-1f7656c69367.png)

**Comment by myhungtos** [comment]
好像是ie瀏覽器的檔案格式

**Comment by myhungtos** [comment]
應該Ms word可以打開

**Comment by hilezir** [comment]
你是用 IE 嗎？IE 我不支持歐！我也沒買 MS Word 這個軟體。

**Comment by myhungtos** [comment]
我用chrome，我再去裝錄桌面軟體

**Comment by myhungtos** [comment]
https://drive.google.com/file/d/1V6NT4BUpVegaZ-dltm5ndEQTT5-UCvq5/view
下載後請通知下架，謝謝。

**Comment by hilezir** [comment]
已要求存取權限

**Comment by myhungtos** [comment]
done. Thanks for the investigation

**Comment by hilezir** [comment]
好，我下載到了。你可以關了。我會再來 debug 看看。

**Comment by hilezir** [comment]
@myhungtos OK我大概知道為什麼了，可能是因為你歐洲監管（我是澳洲），有些介面不同。用來偵測 dialog（彈出框介面）的程式炸了偵測不到。

我小修改一個版本 v0.7.2 你再幫我試試。

**Comment by myhungtos** [comment]
![2020-04-29_114407](https://user-images.githubusercontent.com/63868940/80559022-e4bd2e00-8a0e-11ea-8bb9-61fd2696e0cc.jpg)
歐洲監管可以了，但是英國監管不行，真的是監管的問題，如果要給你看英國監管的下單資訊要截什麼關鍵字給你，謝謝。

**Comment by myhungtos** [comment]
下單介面按開第一次後 可以把上一次設定的按鈕鎖起來嗎，例如都一直維持x1 金額不鎖定用預設， 或者金額跟倍數都鎖起來，等等的組合，謝謝。

**Comment by hilezir** [comment]
> 下單介面按開第一次後 可以把上一次設定的按鈕鎖起來嗎，例如都一直維持x1 金額不鎖定用預設， 或者金額跟倍數都鎖起來，等等的組合，謝謝。

要等我一陣子，最近案子比較多，比較忙一些。

**Comment by hilezir** [comment]
> 下單介面按開第一次後 可以把上一次設定的按鈕鎖起來嗎，例如都一直維持x1 金額不鎖定用預設， 或者金額跟倍數都鎖起來，等等的組合，謝謝。

@myhungtos FYI 近期內將發佈新版本，能夠鎖定「你上次點選的金額與槓桿」，這個功能就能使你實現：每次開啟下單都維持 x1 的場景。

![image](https://user-images.githubusercontent.com/1500206/85063244-701b9a00-b1dc-11ea-8564-6191f77e561a.png)
